Add alert class, expand description of Incident class
JupiterOne/data-model pull request #117
Opened 2021-07-30 13:59 UTC by charlieduong94

2021-07-30 16:33 UTC, benrj approved these changes

2021-07-30 16:43 UTC, tywalch approved these changes

2021-08-02 18:23 UTC, austinkelleher approved these changes
Approved with suggestion/comment.

2021-08-02 18:23 UTC, austinkelleher commented on src/schemas/Alert.json
> +  "$id": "#Alert",
Should an alert have any properties on it that are _not_ properties of `RecordEntity`? Could we use any J1 alert properties as a reference? Maybe we should use `Finding` as a reference too?

I think we should consider having a principal that creating a new class in the data model requires at least one property that differentiates it from the parent class. Thoughts @JupiterOne/integrations?

2021-08-02 19:03 UTC, aiwilliams requested changes

2021-08-02 19:03 UTC, aiwilliams commented on src/schemas/Incident.json
> +  "description": "An operational or security incident. An event that negatively affects the confidentiality, integrity or availability of an organization.",
```suggestion
  "description": "An operational or security incident. An event that negatively affects the confidentiality, integrity or availability of an organization's assets.",
```

2021-08-02 19:03 UTC, aiwilliams commented on src/schemas/Alert.json
> +  "description": "A notice of any unusual or dangerous circumstances that is sent to responsible parties for the purpose of triggering action.",
```suggestion
  "description": "A notice of any unusual or dangerous circumstance that is sent to responsible parties for the purpose of triggering action.",
```

2021-08-02 19:03 UTC, aiwilliams commented on src/schemas/Alert.json
> +  "$id": "#Alert",
It seems to me that the name of the entity is a "property" of the entity that brings additional meaning.

2021-08-02 19:09 UTC, tywalch approved these changes

2021-08-02 20:28 UTC, charlieduong94 commented on src/schemas/Alert.json
> +  "description": "A notice of any unusual or dangerous circumstances that is sent to responsible parties for the purpose of triggering action.",
Thanks! Commited both suggestions!

2021-08-02 21:19 UTC, mknoedel commented on src/schemas/Alert.json
> +  "$id": "#Alert",
I agree with @aiwilliams, The reason why we would have an `Alert` class, is because it makes using J1QL easier for them (`find Alert`). I'm not sure any additional properties should be required.

2021-08-02 21:19 UTC, mknoedel approved these changes

2021-08-03 14:02 UTC, austinkelleher commented on src/schemas/Alert.json
> +  "$id": "#Alert",
I still think we should always question why we are adding a new class that does not have any properties. I'm pretty skeptical that adding new classes without a single standardized property is ideal.

2021-08-03 17:43 UTC, aiwilliams approved these changes

2021-08-03 17:45 UTC, aiwilliams commented on src/schemas/Alert.json
> +  "$id": "#Alert",
I think that's a good practice for sure @austinkelleher. I think in this case, it would be good to have a property indicating the severity of the `Alert`, which I don't think that `RecordEntity` would have on it. @charlieduong94 are there any plans to add some "alert domain" properties?

2021-08-03 17:54 UTC, merged

2021-08-04 13:46 UTC, charlieduong94 commented on src/schemas/Alert.json
> +  "$id": "#Alert",
ATM J1 Alerts will look and feel like a `Finding`, but I wanted to start with a loose definition first and tighten the class as we start to figure out how much of a "catch all" (as Akash put it) the Alert class will be.