Update README.md
JupiterOne/data-model pull request #174
Opened 2022-07-05 23:34 UTC by erkangz

update README with correct doc link and descriptions of type & class

2022-07-06 04:50 UTC, aiwilliams requested changes
This is helpful commentary. I think there is going to need to be some work done in the integration SDK and documentation generators to communicate dynamic values in integrations that do not have a defined set of `_type` values.

2022-07-06 04:50 UTC, aiwilliams commented on README.md
> +The metadata attributes `_type` and `_class` are used to defined what the asset is:
```suggestion
The metadata attributes `_type` and `_class` are used to define what the asset is:
```

2022-07-06 04:50 UTC, aiwilliams commented on README.md
> +  Here are some exceptions:
```suggestion
```

2022-07-06 04:50 UTC, aiwilliams commented on README.md
> +  `_type: 'contractor'` rather than `_type: 'bamboohr_employee'` or `_type: 'bamboohr_contractor'`.
```suggestion
  BambooHR or Rippling. The `Person` entity being created should have `_type: 'employee'` or
  `_type: 'contractor'` rather than `_type: 'bamboohr_employee'` or `_type: 'bamboohr_contractor'`.
```

2022-07-06 04:50 UTC, aiwilliams commented on README.md
> +  examples:
```suggestion
  Another exception is data that comes from an integration with another ITSM, asset discovery tool,
  device management tool, or CMDB. While a system might be a good "source of truth" or "system
  of record," they are not the actual vendor of those devices.
```

2022-07-06 04:50 UTC, aiwilliams commented on README.md
> +    `cisco_switch` instead of `rumble_switch` or `netbox_device`.
```suggestion
  - If a Cisco switch is ingested from **Rumble** or **Netbox**, the `_type` should be
    `cisco_switch` instead of `rumble_switch` or `netbox_device`. 
```

2022-07-06 04:50 UTC, aiwilliams commented on README.md
> +    and Apple iPhone and it would be very confusing to call an iPhone a Google mobile device.
```suggestion
    an Apple iPhone and it would be very confusing to call an iPhone a Google mobile device. 
```

2022-07-06 04:50 UTC, aiwilliams commented on README.md
> +    Instead, it should be `apple_iphone` (if we know what it is), or just using a generic value of
```suggestion
    Instead, it should be `apple_iphone` when the type of device is known or a generic value of
```

2022-07-06 04:50 UTC, aiwilliams commented on README.md
> +  IT or Security terminology to describe the higher level category of the asset.
```suggestion
  IT or Security term to describe the higher level category of the asset.
```

2022-07-06 08:11 UTC, erkangz commented
Thanks for the suggested changes and catching the typos, @aiwilliams. Updated.

2022-07-15 19:48 UTC, ericanagle1 commented
I definitely agree that we will need to do some work on the _type values/and looking into the level of impact but great content overall and will be useful for us to reference!

2022-07-18 19:43 UTC, erkangz commented
@aiwilliams are you good with the changes?

2022-07-18 19:48 UTC, aiwilliams approved these changes

2022-07-19 01:11 UTC, merged